/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daftarmahasiswa;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Menu extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    private Boolean isUpdate = false;
    private int selectedID = -1;
    private ArrayList<Mahasiswa> listMhs;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        listMhs = new ArrayList<>();
        //Dummy
        listMhs.add(new Mahasiswa("14000411", "Udin", "Kalkulus", "A"));
        listMhs.add(new Mahasiswa("14000412", "Mahmud", "Fisika Dasar", "B"));
        listMhs.add(new Mahasiswa("14000413", "Jonathan", "TIB", "F"));
        // Set Table
        table.setModel(setTable());
        // Hide Delete button
        btnDelete.setVisible(false);
    }

    public final DefaultTableModel setTable() {
        Object[] column = {"NIM", "Nama","Matkul","Nilai"};
        DefaultTableModel dataTabel = new DefaultTableModel(null, column);
        for (int i = 0; i < listMhs.size(); i++) {
            Object[] row = new Object[4];
            row[0] = listMhs.get(i).getNim();
            row[1] = listMhs.get(i).getNama();            
            row[2] = listMhs.get(i).getMatkul();
            row[3] = listMhs.get(i).getNilai();

            dataTabel.addRow(row);
        }

        return dataTabel;
    }

    public void insertData() {
        // Get Data
        String nim = txtfldNIM.getText();
        String nama = txtfldNama.getText();
        String matkul = txtfldMatkul.getText();
        String nilai = txtfldNilai.getText();
        
        // data check
        if(nim.length() > 0 && nama.length()> 0 && nilai.length()>0 && matkul.length()>0){
            listMhs.add(new Mahasiswa(nim, nama, matkul, nilai));
            //Update Table
            table.setModel(setTable());

            System.out.println("Insert Success!");
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");   
        }
        //data empty
        else{
            System.out.println("Insert Failed!");
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!");
            
        }
    }

    public void updateData() {
        // Get Data
        String nim = txtfldNIM.getText();
        String nama = txtfldNama.getText();
        String matkul = txtfldMatkul.getText();
        String nilai = txtfldNilai.getText();
        //System.out.println(nim + nama + nilai);
        
        //data check
        if(nim.length() > 0 && nama.length()> 0 && nilai.length()>0){
            listMhs.get(selectedID).setNim(nim);
            listMhs.get(selectedID).setNama(nama);
            listMhs.get(selectedID).setMatkul(matkul);
            listMhs.get(selectedID).setNilai(nilai);
            System.out.println("Update Success!");
            table.setModel(setTable());
            JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
    
        }
        
        //data empty
        else{
            System.out.println("Update Failed!");
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!");
            
        }
        
        
    }
    public void deleteData(int ID) {
        listMhs.remove(ID);
        System.out.println("Delete Success!");
        JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblADDorUPDATE = new javax.swing.JButton();
        txtfldNIM = new javax.swing.JTextField();
        lblNIM = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        txtfldNama = new javax.swing.JTextField();
        lblNilai = new javax.swing.JLabel();
        txtfldNilai = new javax.swing.JTextField();
        scrlpnlUtama = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblMatkul = new javax.swing.JLabel();
        txtfldMatkul = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setFont(new java.awt.Font("MS Gothic", 0, 30)); // NOI18N
        lblJudul.setText("Daftar Mahasiswa");
        lblJudul.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblADDorUPDATE.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        lblADDorUPDATE.setText("Add");
        lblADDorUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblADDorUPDATEActionPerformed(evt);
            }
        });

        txtfldNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldNIMActionPerformed(evt);
            }
        });

        lblNIM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNIM.setText("NIM");

        lblNama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNama.setText("Nama");

        txtfldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldNamaActionPerformed(evt);
            }
        });

        lblNilai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNilai.setText("Nilai");

        txtfldNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldNilaiActionPerformed(evt);
            }
        });

        table.setAutoCreateRowSorter(true);
        table.setFont(new java.awt.Font("MS PGothic", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table.setUpdateSelectionOnSort(false);
        table.setVerifyInputWhenFocusTarget(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        scrlpnlUtama.setViewportView(table);

        btnDelete.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Gill Sans MT", 1, 10)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblMatkul.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMatkul.setText("Mata Kuliah");

        txtfldMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldMatkulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrlpnlUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(lblJudul))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfldNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblNIM)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtfldNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblNama)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtfldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblMatkul)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfldMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblADDorUPDATE)
                                    .addComponent(btnDelete)
                                    .addComponent(btnCancel))))))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lblADDorUPDATE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblJudul)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfldNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNIM))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(txtfldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfldMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMatkul)
                    .addComponent(btnDelete))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfldNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNilai))
                .addGap(5, 5, 5)
                .addComponent(scrlpnlUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfldNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldNIMActionPerformed

    private void txtfldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldNamaActionPerformed

    private void txtfldNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldNilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfldNilaiActionPerformed

    private void lblADDorUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblADDorUPDATEActionPerformed
        // TODO add your handling code here:
        if (isUpdate == false){
            insertData();
            this.txtfldNama.setText("");
            this.txtfldNIM.setText("");
            this.txtfldMatkul.setText("");
            this.txtfldNilai.setText("");
            

        }
        else {
            updateData();
            this.txtfldNama.setText("");
            this.txtfldNIM.setText("");            
            this.txtfldMatkul.setText("");
            this.txtfldNilai.setText("");
            lblADDorUPDATE.setText("Add");
            btnDelete.setVisible(false);
            this.isUpdate = false;
        }
    }//GEN-LAST:event_lblADDorUPDATEActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        this.isUpdate = true;

        //Get Selected Data
        int row = table.getSelectedRow();
        String selectedNim = (table.getModel().getValueAt(row, 0).toString());
        String selectedNama = (table.getModel().getValueAt(row, 1).toString());
        String selectedMatkul = (table.getModel().getValueAt(row, 2).toString());
        String selectedNilai = (table.getModel().getValueAt(row, 3).toString());

        for (int i = 0; i < listMhs.size(); i++) {
            if (selectedNim.equals(listMhs.get(i).getNim())) {
                selectedID = i;
                break;
            }
        }

        //System.out.println(selectedID);
        this.txtfldNIM.setText(selectedNim);
        this.txtfldNama.setText(selectedNama);        
        this.txtfldMatkul.setText(selectedMatkul);
        this.txtfldNilai.setText(selectedNilai);

        lblADDorUPDATE.setText("Update");
        btnDelete.setVisible(true);
    }//GEN-LAST:event_tableMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (isUpdate == true) {
            deleteData(selectedID);
            this.txtfldNama.setText("");
            this.txtfldNIM.setText("");
            this.txtfldMatkul.setText("");
            this.txtfldNilai.setText("");
            lblADDorUPDATE.setText("Add");
            btnDelete.setVisible(false);
            table.setModel(setTable());
            this.isUpdate = false;
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        lblADDorUPDATE.setText("Add");
        this.txtfldNama.setText("");
        this.txtfldNIM.setText("");
        this.txtfldMatkul.setText("");

        this.txtfldNilai.setText("");
        btnDelete.setVisible(false);
        this.isUpdate = false;
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtfldMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldMatkulActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtfldMatkulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lblADDorUPDATE;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblMatkul;
    private javax.swing.JLabel lblNIM;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNilai;
    private javax.swing.JScrollPane scrlpnlUtama;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtfldMatkul;
    private javax.swing.JTextField txtfldNIM;
    private javax.swing.JTextField txtfldNama;
    private javax.swing.JTextField txtfldNilai;
    // End of variables declaration//GEN-END:variables
}
